discussion/discussion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todolist/', include('todolist.urls')),
    path('admin/', admin.site.urls),
]

discussion/todolist/urls.py
from django.urls import path

# import views from the current directory
from . import views

app_name = 'todolist'

# urlpatterns is a list of paths that Django will try to match the requested URL to find the correct view.
urlpatterns = [
    # path() function is passed four arguments, two required: route and view, and two optional: kwargs, and name.
    # route is a string that contains a URL pattern.
    # view is a function that is called when Django matches the requested URL to this route.
    # kwargs is a dictionary of additional arguments that can be passed to the view function.
    # name is the name of the URL that will be used to identify the view.
    path('index', views.index, name='index'),
    path('<int:todoitem_id>/', views.todoitem, name='viewtodoitem'),
    path('register', views.register, name='register'),
    path('change_password', views.change_password, name='change_password'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('add_task', views.add_task, name='add_task'),
    path('<int:todoitem_id>/update_task', views.update_task, name='update_task'),
    path('<int:todoitem_id>/delete_task', views.delete_task, name='delete_task'),
    path('add_event', views.add_event, name='add_event'),
    path('events/<int:event_id>/', views.view_event, name='viewevent'),
    path('events/<int:event_id>/update_event', views.update_event, name='update_event'),
    path('events/<int:event_id>/delete_event', views.delete_event, name='delete_event'),

]

discussion/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} To Do App {% endblock %}</title>

    <!--Bootstrap Link-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">


</head>
<body>
    <!--    <h1>Hello Batch 278!</h1>-->
    <!--The "include" keyword unlike the "extends" keyword allows to inject specific templates in certain sections of a page-->
    {% include 'navbar.html' %}

    {% block content %}
    <!--Block denotes a placeholder for content that will be filled in by the template that extends this base template.-->

    {% endblock %}


    <!--    Sample only to show that we can add many block place holder-->
    <!--    {% block body %}-->
    <!--Block denotes a placeholder for content that will be filled in by the template that extends this base template.-->

    <!--    {% endblock %}-->


    <!--    bootstrap script->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
</body>
</html></body>

discussion/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'todolist:index' %}">To Do App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">

        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:add_task' %}">Add Task</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:add_event' %}">Add Event</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:logout' %}">Logout</a>
        </li>

        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:login' %}">Login</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:register' %}">Register</a>
        </li>
        {% endif %}

      </ul>
    </div>
  </div>
</nav>