discussion/discussion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todolist/', include('todolist.urls')),
    path('admin/', admin.site.urls),
]

discussion/todolist/urls.py
from django.urls import path

# import views from the current directory
from . import views

app_name = 'todolist'

# urlpatterns is a list of paths that Django will try to match the requested URL to find the correct view.
urlpatterns = [
    # path() function is passed four arguments, two required: route and view, and two optional: kwargs, and name.
    # route is a string that contains a URL pattern.
    # view is a function that is called when Django matches the requested URL to this route.
    # kwargs is a dictionary of additional arguments that can be passed to the view function.
    # name is the name of the URL that will be used to identify the view.
    path('index', views.index, name='index'),
    path('<int:todoitem_id>/', views.todoitem, name='viewtodoitem'),
    path('register', views.register, name='register'),
    path('change_password', views.change_password, name='change_password'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('add_task', views.add_task, name='add_task'),
    path('<int:todoitem_id>/update_task', views.update_task, name='update_task'),
    path('<int:todoitem_id>/delete_task', views.delete_task, name='delete_task'),
    path('add_event', views.add_event, name='add_event'),
    path('events/<int:event_id>/', views.view_event, name='viewevent'),
    path('events/<int:event_id>/update_event', views.update_event, name='update_event'),
    path('events/<int:event_id>/delete_event', views.delete_event, name='delete_event'),

]

discussion/todolist/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User


class ToDoItem(models.Model):
    task_name = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    status = models.CharField(max_length=50, default="Pending")
    date_created = models.DateTimeField('date created', auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.RESTRICT, default="")


class Events(models.Model):
    event_name = models.CharField(max_length=20)
    description = models.CharField(max_length=200)
    status = models.CharField(max_length=50, default="Pending")
    date_created = models.DateTimeField('date created', auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.RESTRICT, default="")

discussion/todolist/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(label="username", max_length=20)
    password = forms.CharField(label="password", max_length=20)


class AddTaskForm(forms.Form):
    task_name = forms.CharField(label="task_name", max_length=50)
    description = forms.CharField(label="description", max_length=200)


class UpdateTaskForm(forms.Form):
    task_name = forms.CharField(label="task_name", max_length=50)
    description = forms.CharField(label="description", max_length=200)
    status = forms.CharField(label="status", max_length=50)


class RegisterForm(forms.Form):
    first_name = forms.CharField(label="first_name", max_length=20)
    last_name = forms.CharField(label="last_name", max_length=20)
    email = forms.CharField(label="email", max_length=20)
    username = forms.CharField(label="username", max_length=20)
    password1 = forms.CharField(label="password1", max_length=20)
    password2 = forms.CharField(label="password2", max_length=20)


class AddEventForm(forms.Form):
    event_name = forms.CharField(label="event_name", max_length=50)
    description = forms.CharField(label="description", max_length=200)


class UpdateEventForm(forms.Form):
    event_name = forms.CharField(label="event_name", max_length=50)
    description = forms.CharField(label="description", max_length=200)
    status = forms.CharField(label="status", max_length=50)

discussion/todolist/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib import messages

# Create your views here.

# The "from" keyword is used to import a module or a function from a module.
from django.http import HttpResponse

import time

# Local imports
from .models import ToDoItem, Events

# import the built-in user model
from django.contrib.auth.models import User

# import the authentication module
from django.contrib.auth import authenticate, login, logout

# to use the template created
# from django.template import loader

# to use the model_to_dict function
from django.forms.models import model_to_dict

# import the LoginForm class
from .forms import LoginForm, AddTaskForm, UpdateTaskForm, RegisterForm, AddEventForm, UpdateEventForm

from django.utils import timezone


def index(request):
    todoitem_list = ToDoItem.objects.filter(user_id=request.user.id)
    events_list = Events.objects.filter(user_id=request.user.id)
    # template = loader.get_template("index.html")
    context = {
        'todoitem_list': todoitem_list,
        'events_list': events_list,
        'user': request.user,
    }
    # output = ", ".join([todoitem.task_name for todoitem in todoitem_list])
    # render(request, route_template, context)
    return render(request, "index.html", context)


def todoitem(request, todoitem_id):
    # response = f"You are viewing the details of {todoitem_id}"
    # return HttpResponse(response)

    todoitem = get_object_or_404(ToDoItem, pk=todoitem_id)

    return render(request, "todoitem.html", model_to_dict(todoitem))


# this function is responsible for registering on our application
def register(request):
    context = {}

    if request.method == "POST":
        form = RegisterForm(request.POST)

        if not form.is_valid():
            form = RegisterForm()

        else:
            # get the form data
            user = User()
            user.username = form.cleaned_data['username']
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.email = form.cleaned_data['email']
            password = (form.cleaned_data['password1'])
            user.is_staff = False
            user.is_active = True

            # check if the password and confirm password match
            if password == form.cleaned_data['password2']:
                # check if the user is already registered
                if User.objects.filter(username=user.username).exists():
                    context['error1'] = "Username already exists"
                elif User.objects.filter(email=user.email).exists():
                    context['error2'] = "Email already exists"
                else:
                    # to save our user
                    user.set_password(password)
                    user.save()
                    context['success'] = True
            else:
                context['error3'] = "Passwords do not match"

    return render(request, 'register.html', context)

# old register function
# def register(request):
#     users = User.objects.all()
#     is_user_registered = False
#
#     user = User()
#     user.username = "janedoe"
#     user.first_name = "Jane"
#     user.last_name = "Doe"
#     user.email = "jane@mail.com"
#     user.set_password("jane1234")
#     user.is_staff = False
#     user.is_active = True
#
#     # check if the user is already registered
#     for indiv_user in users:
#         if indiv_user.username == user.username:
#             is_user_registered = True
#             break
#     if not is_user_registered:
#         # to save our user
#         user.save()
#
#     context = {
#         'is_user_registered': is_user_registered,
#         'first_name': user.first_name,
#         'last_name': user.last_name
#     }
#
#     return render(request, 'register.html', context)


def change_password(request):
    is_user_authenticated = False

    user = authenticate(request, username='johndoe', password='john12345')
    if user is not None:
        authenticated_user = User.objects.get(username='johndoe')
        authenticated_user.set_password('john123456')
        authenticated_user.save()
        is_user_authenticated = True

    context = {
        'is_user_authenticated': is_user_authenticated
    }

    return render(request, 'change_password.html', context)


def login_user(request):
    context = {}

    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid() == False:
            form = LoginForm()

        else:
            print(form)
            # process the data in form.cleaned_data as required
            # it retrieves the username and password from the form
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(request, username=username, password=password)

            if user is not None:
                context = {
                    'username': username,
                    'password': password
                }

                login(request, user)
                return redirect("todolist:index")
            else:
                context = {
                    'error': True
                }

    return render(request, 'login.html', context)


def logout_user(request):
    logout(request)
    return redirect("todolist:index")


def add_task(request):
    context = {}

    if request.method == 'POST':
        form = AddTaskForm(request.POST)

        if not form.is_valid():
            form = AddTaskForm()

        else:
            task_name = form.cleaned_data['task_name']
            description = form.cleaned_data['description']

            duplicates = ToDoItem.objects.filter(task_name=task_name, user_id=request.user.id)

            if not duplicates:
                # create a new task and save it to the database
                ToDoItem.objects.create(task_name=task_name, description=description, date_created=timezone.now(),
                                        user_id=request.user.id)

                return redirect("todolist:index")

            else:
                context = {
                    'error': True
                }

    return render(request, 'add_task.html', context)


def update_task(request, todoitem_id):

    todoitem = ToDoItem.objects.filter(pk=todoitem_id)

    print(todoitem)

    context = {
        'user': request.user,
        'todoitem_id': todoitem_id,
        'task_name': todoitem[0].task_name,
        'description': todoitem[0].description,
        'status': todoitem[0].status
    }

    if request.method == 'POST':
        form = UpdateTaskForm(request.POST)

        if not form.is_valid():
            form = UpdateTaskForm()

        else:
            task_name = form.cleaned_data['task_name']
            description = form.cleaned_data['description']
            status = form.cleaned_data['status']

            if todoitem:
                todoitem[0].task_name = task_name
                todoitem[0].description = description
                todoitem[0].status = status

                todoitem[0].save()

                return redirect("todolist:viewtodoitem", todoitem_id=todoitem_id)

            else:
                context = {
                    'error': True
                }

    return render(request, 'update_task.html', context)


def delete_task(request, todoitem_id):

    todoitem = ToDoItem.objects.filter(pk=todoitem_id).delete()

    return redirect("todolist:index")


def add_event(request):
    context = {}

    if request.method == 'POST':
        form = AddEventForm(request.POST)

        if not form.is_valid():
            form = AddEventForm()

        else:
            event_name = form.cleaned_data['event_name']
            description = form.cleaned_data['description']

            duplicates = Events.objects.filter(event_name=event_name, user_id=request.user.id)

            if not duplicates:
                # create a new event and save it to the database
                Events.objects.create(event_name=event_name, description=description, date_created=timezone.now(),
                                      user_id=request.user.id)

                return redirect("todolist:index")

            else:
                context = {
                    'error': True
                }

    return render(request, 'add_event.html', context)


def view_event(request, event_id):

    event = Events.objects.filter(pk=event_id)

    context = {
        'user': request.user,
        'event_id': event_id,
        'event_name': event[0].event_name,
        'description': event[0].description,
        'date_created': event[0].date_created,
        'status': event[0].status
    }

    return render(request, 'view_event.html', context)


def update_event(request, event_id):

    event = Events.objects.filter(pk=event_id)

    context = {
        'user': request.user,
        'event_id': event_id,
        'event_name': event[0].event_name,
        'description': event[0].description,
        'status': event[0].status
    }

    if request.method == 'POST':
        form = UpdateEventForm(request.POST)

        if not form.is_valid():
            form = UpdateEventForm()

        else:
            event_name = form.cleaned_data['event_name']
            description = form.cleaned_data['description']
            status = form.cleaned_data['status']

            if event:
                event[0].event_name = event_name
                event[0].description = description
                event[0].status = status

                event[0].save()

                return redirect("todolist:viewevent", event_id=event_id)

            else:
                context = {
                    'error': True
                }

    return render(request, 'update_event.html', context)


def delete_event(request, event_id):

discussion/todolist/templates/add_event.html
{% extends 'base.html' %}

{% block title %}Add Event{% endblock %}

{% block content %}
<div class="container">
        <div class="row">
            <div class="col-6 offset-3">

                   <!--Display error message if any-->
                {% if error %}
                    <div class="alert alert-danger mt-3" role="alert">
                         <p class="text-danger">Duplicate event found!</p>
                    </div>
                {% endif %}
                <form action="{% url 'todolist:add_event' %}" method="POST">

                        {% csrf_token %}

                        <div class="mb-3">
                            <label for="event_name">Event Name: </label>
                            <input class="form-control" id="event_name" type="text" name="event_name" value="{{ event_name }}" maxlength="50" required>
                        </div>

                        <div class="mb-3">
                            <label for="description">Description: </label>
                            <textarea class="form-control" name="description" value="{{ description }}" required></textarea>
                        </div>

                        <div class="text-center">
                            <input class="btn btn-success" type="submit" value="Add Event">
                        </div>

                </form>
            </div>
        </div>
    </div>
{% endblock %}

discussion/todolist/templates/add_task.html
{% extends 'base.html' %}

{% block title %}Add Task{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-6 offset-3">

                   <!--Display error message if any-->
                {% if error %}
                    <div class="alert alert-danger mt-3" role="alert">
                         <p class="text-danger">Duplicate task found!</p>
                    </div>
                {% endif %}
                <form action="{% url 'todolist:add_task' %}" method="POST">

                        {% csrf_token %}

                        <div class="mb-3">
                            <label for="task_name">Task Name: </label>
                            <input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
                        </div>

                        <div class="mb-3">
                            <label for="description">Description: </label>
                            <textarea class="form-control" name="description" value="{{ description }}" required></textarea>
                        </div>

                        <div class="text-center">
                            <input class="btn btn-success" type="submit" value="Add Task">
                        </div>

                </form>
            </div>
        </div>
    </div>
{% endblock %}

discussion/todolist/templates/change_password.html
{% if is_user_authenticated == False %}
  <h1>Invalid User Credentials!</h1>
  <p>Check if the username and password is correct!</p>
{% else %}
  <h1>User password successfully updated!</h1>
  <p>The password has been successfully updated!</p>
{% endif %}
<!--  -->

discussion/todolist/templates/index.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}
    {% if user.is_anonymous == False %}
    <h1 class="text-center my-3">Welcome {{user.first_name}} {{user.last_name}}!</h1>
        {% if events_list|length == 0 and todoitem_list %}
        <div class="container">
            <div class="row">
                <h3 class="text-center mb-3">My Tasks</h3>
                <ul class=" list-group text-center col-lg-4 offset-lg-4">
                {% for todoitem in todoitem_list %}
                 <li class="list-group-item"><a class="text-decoration-none" href = "{% url 'todolist:viewtodoitem' todoitem.id %}">{{todoitem.task_name}}</a></li>
                {% endfor%}
                </ul>
            </div>
         </div>

        <div class="container mt-3">
            <div class="row">
                <h3 class="text-center mb-3">My Events</h3>
                 <p class="text-center my-3">No events have been created.</p>
            </div>
        </div>

       {% elif todoitem_list|length == 0 and events_list %}
        <div class="container">
            <div class="row">
                <h3 class="text-center mb-3">My Tasks</h3>
                <p class="text-center my-3">No tasks have been created.</p>
            </div>
        </div>

        <div class="container mt-3">
            <div class="row">
                <h3 class="text-center mb-3">My Events</h3>
                 <ul class=" list-group text-center col-lg-4 offset-lg-4">
                {% for events_item in events_list %}
                 <li class="list-group-item"><a class="text-decoration-none" href = "{% url 'todolist:viewevent' events_item.id %}">{{events_item.event_name}}</a></li>
                {% endfor%}
                </ul>
            </div>
        </div>

        {% elif todoitem_list and events_list %}
        <div class="container">
            <div class="row">
                <h3 class="text-center mb-3">My Tasks</h3>
                <ul class=" list-group text-center col-lg-4 offset-lg-4">
                {% for todoitem in todoitem_list %}
                 <li class="list-group-item"><a class="text-decoration-none" href = "{% url 'todolist:viewtodoitem' todoitem.id %}">{{todoitem.task_name}}</a></li>
                {% endfor%}
                </ul>
            </div>
        </div>

        <div class="container mt-3">
            <div class="row">
                <h3 class="text-center mb-3">My Events</h3>
                 <ul class=" list-group text-center col-lg-4 offset-lg-4">
                {% for events_item in events_list %}
                 <li class="list-group-item"><a class="text-decoration-none" href = "{% url 'todolist:viewevent' events_item.id %}">{{events_item.event_name}}</a></li>
                {% endfor%}
                </ul>
            </div>
        </div>

        {% else %}
        <p class="text-center my-3">No tasks have been created.</p>
        <p class="text-center my-3">No events have been created.</p>
        {% endif %}


{%else%}
    <h1 class="text-center my-3">You are not authorized to access this page.</h1>
    <p class="text-center my-3">Kindly login <a href = "{% url 'todolist:login' %}">here</a>.</p>
{% endif %}
{% endblock %}

discussion/todolist/templates/login.html
{% extends 'base.html' %}

{% block title%}Login{% endblock %}

{% block content%}
    <h1 class="text-center my-3">Login Form</h1>
    <div class="container">
        <div class="row">
            <div class="col-6 offset-3">

                <!--Display error message if any-->
                {% if error %}
                    <div class="alert alert-danger" role="alert">
                         <p class="text-danger">Invalid Credentials, please check your username and password first</p>
                    </div>
                {% endif %}
                <form action="{% url 'todolist:login' %}" method="POST">
                    <!--this template tag is used to prevent cross-site request forgery (CSRF)-->
                    <!-- CSRF occurs when a malicious website sends a request to a trusted website on behalf of a user who is logged in to the trusted website.-->
                    {% csrf_token %}
                  <div class="mb-3">
                    <label for="username" class="form-label">Username:</label>
                    <input type="text" class="form-control" id="username" value="{{ username }}" name="username" maxlength="20" required>
                  </div>
                  <div class="mb-3">
                    <label for="password" class="form-label">Password:</label>
                    <input type="password" class="form-control" id="password" value="{{ password }}" name="password" maxlength="20" required>
                  </div>
                  <button type="submit" class="btn btn-primary">Login</button>

                </form>
            </div>
        </div>
    </div>
{% endblock %}

discussion/todolist/templates/register.html
{% extends 'base.html' %}

{% block title%}Register{% endblock %}

{% block content%}
    <h1 class="text-center my-3">Registration Form</h1>
    <div class="container">
        <div class="row">
            <div class="col-6 offset-3">

                <!--Display error message if any-->
                {%if error1 %}
                    <div class="alert alert-danger" role="alert">
                        <p class="text-danger">Duplicate Entry! Username must be unique.</p>
                    </div>
                {% elif error2 %}
                    <div class="alert alert-danger" role="alert">
                        <p class="text-danger">Duplicate Entry! Email must be unique.</p>
                    </div>
                {% elif error3 %}
                    <div class="alert alert-danger" role="alert">
                        <p class="text-danger">Password doesn't match!</p>
                    </div>
                {% endif %}

                <!-- Display success message if any -->
                {% if success %}
                    <div class="alert alert-success" role="alert">
                        <p class="text-success">Successfully registered. You may now login <a href="{% url 'todolist:login' %}">here</a>.</p>
                    </div>
                {% endif %}
                <form action="{% url 'todolist:register' %}" method="POST">
                    {% csrf_token %}

                    <div class="mb-3">
                        <label for="first_name" class="form-label">First Name:</label>
                        <input type="text" class="form-control" id="first_name" value="{{ first_name }}" name="first_name" maxlength="20" required>
                    </div>

                    <div class="mb-3">
                        <label for="last_name" class="form-label">Last name:</label>
                        <input type="text" class="form-control" id="last_name" value="{{ last_name }}" name="last_name" maxlength="20" required>
                    </div>

                    <div class="mb-3">
                        <label for="email" class="form-label">Email Address:</label>
                        <input type="text" class="form-control" id="email" value="{{ email }}" name="email" maxlength="20" required>
                    </div>

                    <div class="mb-3">
                        <label for="username" class="form-label">Username:</label>
                        <input type="text" class="form-control" id="username" value="{{ username }}" name="username" maxlength="20" required>
                    </div>
                    <div class="mb-3">
                        <label for="password1" class="form-label">Password:</label>
                        <input type="password" class="form-control" id="password1" value="{{ password1 }}" name="password1" maxlength="20" required>
                    </div>

                    <div class="mb-3">
                        <label for="password2" class="form-label">Re-enter Password:</label>
                        <input type="password" class="form-control" id="password2" value="{{ password2 }}" name="password2" maxlength="20" required>
                    </div>

                   <div class="text-center">
                            <input class="btn btn-success" type="submit" value="Register">
                        </div>

                </form>
            </div>
        </div>
    </div>
{% endblock %}











<!--{% if is_user_registered == False %}-->
<!--<h1>User Successfully Created!</h1>-->

<!--<p> The account for {{first_name}} {{last_name}} has been created. </p>-->



<!--{% else %}-->
<!--<h1> Duplicate User Found! </h1>-->
<!--<p> The account for {{first_name}} {{last_name}} already exists. User Creation unsuccessful.</p>-->
<!--{% endif %}-->

discussion/todolist/templates/todoitem.html
{% extends "base.html" %}

{% block title %}My Tasks{% endblock %}

{% block content %}

<div class="text-center mt-3">
    <h1>{{task_name}}</h1>

    <h3>Description:</h3>
    <p>{{description}}</p>

    <h3>Status:</h3>
    <p>{{status}}</p>

    <button class="btn bg-success mx-1">
        <a class="text-decoration-none" href="{% url 'todolist:update_task' id %}">Update Task</a>
    </button>

    <button class="btn bg-danger mx-1">
        <a class="text-decoration-none" href="{% url 'todolist:delete_task' id %}">Delete Task</a>
    </button>

    <button class="btn btn-warning mx-1">
        <a class="text-decoration-none" href="{% url 'todolist:index' %}">Back to index page!</a>
    </button>
</div>

{% endblock %}

discussion/todolist/templates/update_event.html
{% extends "base.html" %}

{% block title %}Update Event{% endblock %}

{% block content %}

    {% if user.is_anonymous == False %}
        <div class="container">
            <div class="row">
                <div class="col-6 offset-3">
                    <h1>Update Task</h1>

                     <!--Display error message if any-->
                    {% if error %}
                        <div class="alert alert-danger" role="alert">
                             <p class="text-danger">Error on updating event. Please try again!</p>
                        </div>
                    {% endif %}
                    <form action="{% url 'todolist:update_event' event_id %}" method="post">
                        {% csrf_token %}

                        <div class="mb-3">
                            <label for="event_name">Event Name: </label>
                            <input class="form-control" id="event_name" type="text" name="event_name" value="{{ event_name }}" maxlength="50" required>
                        </div>

                        <div class="mb-3">
                            <label for="description">Description: </label>
                            <textarea class="form-control" name="description" required>{{ description }}</textarea>
                        </div>

                        <div class="mb-3">
                            <label for="status">Status: </label>
                            <input class="form-control" id="status" type="text" name="status" value="{{ status }}" maxlength="50" required>
                        </div>

                        <div class="text-center">
                            <input class="btn btn-success" type="submit" value="Update Event">
                        </div>

                    </form>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}

discussion/todolist/templates/update_task.html
{% extends "base.html" %}

{% block title %}Update Task{% endblock %}

{% block content %}

    {% if user.is_anonymous == False %}
        <div class="container">
            <div class="row">
                <div class="col-6 offset-3">
                    <h1>Update Task</h1>

                     <!--Display error message if any-->
                    {% if error %}
                        <div class="alert alert-danger" role="alert">
                             <p class="text-danger">Task not found!</p>
                        </div>
                    {% endif %}
                    <form action="{% url 'todolist:update_task' todoitem_id %}" method="post">
                        {% csrf_token %}

                        <div class="mb-3">
                            <label for="task_name">Task Name: </label>
                            <input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
                        </div>

                        <div class="mb-3">
                            <label for="description">Description: </label>
                            <textarea class="form-control" name="description" required>{{ description }}</textarea>
                        </div>

                        <div class="mb-3">
                            <label for="status">Status: </label>
                            <input class="form-control" id="status" type="text" name="status" value="{{ status }}" maxlength="50" required>
                        </div>

                        <div class="text-center">
                            <input class="btn btn-success" type="submit" value="Update Task">
                        </div>

                    </form>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}

discussion/todolist/templates/view_event.html
{% extends "base.html" %}

{% block title %}My Events{% endblock %}

{% block content %}

<div class="text-center mt-3">
    <h1>{{event_name}}</h1>

    <h3>Description:</h3>
    <p>{{description}}</p>

    <h3>Status:</h3>
    <p>{{status}}</p>

    <button class="btn bg-success mx-1">
        <a class="text-decoration-none" href="{% url 'todolist:update_event' event_id %}">Update Event</a>
    </button>

    <button class="btn bg-danger mx-1">
           <a class="text-decoration-none" href="{% url 'todolist:delete_event' event_id %}">Delete Event</a>
    </button>

    <button class="btn btn-warning mx-1">
        <a class="text-decoration-none" href="{% url 'todolist:index' %}">Back to index page!</a>
    </button>
</div>

{% endblock %}